Attempt to address kv test flakiness around mount upgrade errors
CONT  TestKVPatchCommand_CAS/right_version
    kv_test.go:1034: Error making API request.

        URL: PUT https://127.0.0.1:40855/v1/kv/data/foo
        Code: 400. Errors:

        * Upgrading from non-versioned to versioned data. This backend will be unavailable for a brief period and will resume service shortly