Add in error variables for the test failures message
When tested with the -race flag in travis it was properly catching that
these arguments to Errorf had not been set properly.

```
command/ssh_test.go:143: Errorf format %q reads arg #1, but call has
only 0 args
```